luci-app-aliddns : bump to 0.4.0-1

diff --git a/luci-app-aliddns/files/root/usr/sbin/aliddns b/luci-app-aliddns/files/root/usr/sbin/aliddns
--- a/luci-app-aliddns/files/root/usr/sbin/aliddns
+++ b/luci-app-aliddns/files/root/usr/sbin/aliddns
@@ -16,15 +16,29 @@ uci_bool_by_name() {
 }
 
 intelnetip() {
-	tmp_ip=`curl -sL --connect-timeout 3   ns1.dnspod.net:6666`
+	tmp_ip=`curl -sL --connect-timeout 3 members.3322.org/dyndns/getip`
 	if [ "Z$tmp_ip" == "Z" ]; then
-		tmp_ip=`curl -sL --connect-timeout 3 members.3322.org/dyndns/getip`
+		tmp_ip=`curl -sL --connect-timeout 3   api-ipv4.ip.sb/ip`
 	fi
 	if [ "Z$tmp_ip" == "Z" ]; then
-		tmp_ip=`curl -sL --connect-timeout 3 14.215.150.17:6666`
+		tmp_ip=`curl -sL --connect-timeout 3 v4.myip.la`
 	fi
 	if [ "Z$tmp_ip" == "Z" ]; then
 		tmp_ip=`curl -sL --connect-timeout 3 whatismyip.akamai.com`
+	fi
+	echo -n $tmp_ip
+}
+
+intelnetip6() {
+	tmp_ip=`curl -sL --connect-timeout 3   ipv6.whatismyip.akamai.com`
+	if [ "Z$tmp_ip" == "Z" ]; then
+		tmp_ip=`curl -sL --connect-timeout 3 speed.neu6.edu.cn/getIP.php`
+	fi
+	if [ "Z$tmp_ip" == "Z" ]; then
+		tmp_ip=`curl -sL --connect-timeout 3 v6.ident.me`
+	fi
+	if [ "Z$tmp_ip" == "Z" ]; then
+		tmp_ip=`curl -sL --connect-timeout 3 api-ipv6.ip.sb/ip`
 	fi
 	echo -n $tmp_ip
 }
@@ -41,6 +55,22 @@ resolve2ip() {
 	fi
 	if [ "Z$tmp_ip" == "Z" ]; then
 		tmp_ip=`curl -sL --connect-timeout 3 "119.29.29.29/d?dn=$domain"`
+	fi
+	echo -n $tmp_ip
+}
+
+resolve2ip6() {
+	# resolve2ip6 domain<string>
+	domain=$1
+	tmp_ip=`nslookup    $domain ns1.alidns.com 2>/dev/null | sed '/^Server/d; /#53$/d' | grep -oE '([0-9A-Fa-f]{0,4}:){2,7}([0-9A-Fa-f]{1,4}$|((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4})' | tail -n1`
+	if [ "Z$tmp_ip" == "Z" ]; then
+		tmp_ip=`nslookup $domain ns2.alidns.com  2>/dev/null | sed '/^Server/d; /#53$/d' | grep -oE '([0-9A-Fa-f]{0,4}:){2,7}([0-9A-Fa-f]{1,4}$|((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4})' | tail -n1`
+	fi
+	if [ "Z$tmp_ip" == "Z" ]; then
+		tmp_ip=`nslookup $domain 114.114.115.115 2>/dev/null | sed '/^Server/d; /#53$/d' | grep -oE '([0-9A-Fa-f]{0,4}:){2,7}([0-9A-Fa-f]{1,4}$|((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4})' | tail -n1`
+	fi
+	if [ "Z$tmp_ip" == "Z" ]; then
+		tmp_ip=`curl -sL --connect-timeout 3 "119.29.29.29/d?dn=$domain&type=AAAA"`
 	fi
 	echo -n $tmp_ip
 }
@@ -64,6 +94,27 @@ check_aliddns() {
 		return 1
 	fi
 }
+
+check_aliddns6() {
+	echo "$DATE WAN6-IP: ${ip6}"
+	if [ "Z$ip6" == "Z" ]; then
+		echo "$DATE ERROR, cant get WAN6-IP..."
+		return 0
+	fi
+	current_ip6=$(resolve2ip6 "$sub_dm.$main_dm")
+	if [ "Z$current_ip6" == "Z" ]; then
+		rrid6='' # NO Resolve IP Means new Record_ID
+	fi
+	echo "$DATE DOMAIN-IP6: ${current_ip6}"
+	if [ "Z$ip6" == "Z$current_ip6" ]; then
+		echo "$DATE IPv6 dont need UPDATE..."
+		return 0
+	else
+		echo "$DATE UPDATING AAAA..."
+		return 1
+	fi
+}
+
 
 urlencode() {
 	# urlencode url<string>
@@ -89,7 +140,11 @@ get_recordid() {
 }
 
 query_recordid() {
-	send_request "DescribeSubDomainRecords" "SignatureMethod=HMAC-SHA1&SignatureNonce=$timestamp&SignatureVersion=1.0&SubDomain=$sub_dm.$main_dm&Timestamp=$timestamp"
+	send_request "DescribeSubDomainRecords" "SignatureMethod=HMAC-SHA1&SignatureNonce=$timestamp&SignatureVersion=1.0&SubDomain=$sub_dm.$main_dm&Timestamp=$timestamp&Type=A"
+}
+
+query_recordid6() {
+	send_request "DescribeSubDomainRecords" "SignatureMethod=HMAC-SHA1&SignatureNonce=$timestamp&SignatureVersion=1.0&SubDomain=$sub_dm.$main_dm&Timestamp=$timestamp&Type=AAAA"
 }
 
 update_record() {
@@ -98,6 +153,14 @@ update_record() {
 
 add_record() {
 	send_request "AddDomainRecord&DomainName=$main_dm" "RR=$sub_dm&SignatureMethod=HMAC-SHA1&SignatureNonce=$timestamp&SignatureVersion=1.0&Timestamp=$timestamp&Type=A&Value=$ip"
+}
+
+update_record6() {
+	send_request "UpdateDomainRecord" "RR=$sub_dm&RecordId=$1&SignatureMethod=HMAC-SHA1&SignatureNonce=$timestamp&SignatureVersion=1.0&Timestamp=$timestamp&Type=AAAA&Value=$ip6"
+}
+
+add_record6() {
+	send_request "AddDomainRecord&DomainName=$main_dm" "RR=$sub_dm&SignatureMethod=HMAC-SHA1&SignatureNonce=$timestamp&SignatureVersion=1.0&Timestamp=$timestamp&Type=AAAA&Value=$ip6"
 }
 
 del_record() {
@@ -134,6 +197,28 @@ do_ddns_record() {
 	fi
 }
 
+do_ddns_record6() {
+	if [ "Z$rrid6" == "Z" ]; then
+		rrid6=`query_recordid6 | get_recordid`
+	fi
+	if [ "Z$rrid6" == "Z" ]; then
+		rrid6=`add_record6 | get_recordid`
+		echo "$DATE ADD record $rrid6"
+	else
+		update_record6 $rrid6 >/dev/null 2>&1
+		echo "$DATE UPDATE record $rrid6"
+	fi
+	if [ "Z$rrid6" == "Z" ]; then
+		# failed
+		echo "$DATE # ERROR, Please Check Config/Time"
+	else
+		# save rrid6
+		uci set aliddns.base.record_id6=$rrid6
+		uci commit aliddns
+		echo "$DATE # UPDATED($ip6)"
+	fi
+}
+
 clean_log() {
 	if [ $(cat $log_file 2>/dev/null | wc -l) -ge 16 ]; then
 		rm -f $log_file && touch $log_file
@@ -141,12 +226,16 @@ clean_log() {
 	fi
 }
 
-[ -x /usr/bin/openssl -a -x /usr/bin/curl -a -x /bin/sed ] ||
-	( echo "Need [ openssl + curl + sed ]" && exit 1 )
+[ -x /usr/bin/openssl -a -x /usr/bin/curl -a -x /bin/sed ] || {
+ echo "Need [ openssl + curl + sed ]"
+ exit 1
+}
+
 
 ak_id=$(uci_get_by_name   base app_key)
 ak_sec=$(uci_get_by_name  base app_secret)
 rrid=$(uci_get_by_name    base record_id)
+rrid6=$(uci_get_by_name   base record_id6)
 main_dm=$(uci_get_by_name base main_domain)
 sub_dm=$(uci_get_by_name  base sub_domain)
 
@@ -154,7 +243,7 @@ iface=$(uci_get_by_name   base interface)
 if [ "Z$iface" == "Zinternet" -o "Z$iface" == "Z" ]; then
 	ip=$(intelnetip)
 else
-	ip=$(ubus call network.interface.$iface status | grep '"address"' | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
+	ip=$(ubus call network.interface.$iface status | grep '"address"' | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
 fi
 
 DATE=$(date +'%Y-%m-%d %H:%M:%S')
@@ -162,3 +251,14 @@ timestamp=$(date -u "+%Y-%m-%dT%H%%3A%M%%3A%SZ")
 
 clean_log
 check_aliddns || do_ddns_record
+
+# exit if ipv6 not-enabled
+uci_bool_by_name base ipv6 || exit 0
+
+if [ "Z$iface" == "Zinternet" -o "Z$iface" == "Z" ]; then
+	ip6=`urlencode $(intelnetip6)`
+else
+	ip6=`urlencode $(ubus call network.interface.$iface status | grep '"address"' | grep -oE '([0-9A-Fa-f]{0,4}:){2,7}([0-9A-Fa-f]{1,4}$|((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4})' | head -1)`
+fi
+
+check_aliddns6 || do_ddns_record6
